version: '3.8'

services:
  sharpistai:
    image: sharpistai:latest
    deploy:
      replicas: 1  # Adjust the number of replicas as needed
      restart_policy:
        condition: any
    ports:
      - "9000:80"
    environment:
      - PYTHONUNBUFFERED=1
