name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set Tag in evn variable
    # docker build . --file Dockerfile --tag dellicon/sharpistai:latest
      run: |
          echo "${GITHUB_SHA:0:7}" > TAG
          docker build . --file Dockerfile --tag dellicon/sharpistai:latest

    - name: Docker Login
      # run: docker login dellicon -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u dellicon -p dckr_pat_1bnUqwkI6wKnzPpbtEUZkx1IsQs
      # For the above command, you need to create a secret in the repository settings with the name DOCKER_PASSWORD and the value as your Docker Hub password.
    
    - name: Docker Push
      run: docker push dellicon/sharpistai:latest
  